import "./addClass.js";
import "./attr.js";
import "./hasClass.js";
import "./html.js";
import "./prop.js";
import "./removeAttr.js";
import "./removeClass.js";
import "./removeProp.js";
import "./toggleClass.js";
